---
name: "iTunes"
guid: "eb5d7894-8eef-4b36-aa6f-5d124e828ce1"
version: "1.0.0.0"
targetAbi: "10.8.0.0"
framework: "net6.0"
overview: "Short description about your plugin"
description: >
  Plugin to fetch metadata from iTunes
category: "General"
owner: "Shadowghost"
artifacts:
- "HtmlAgilityPack.dll"
- "Jellyfin.Plugin.ITunes.dll"
changelog: >
  1.0.0.0:
    * add album image fetching
    * add artist image fetching
